const BASE_URL='https://marimexbackend.vercel.app';
export const MARBEL_URL=BASE_URL+'/api/marble';
export const MARBEL_TAGS_URL=MARBEL_URL+'/tags';
export const MARBEL_BY_SEARCH_URL=MARBEL_URL+'/search/';
export const MARBEL_BY_TAG_URL=MARBEL_URL+'/tags/';
export const MARBEL_BY_ID_URL=MARBEL_URL+'/';
export const USER_LOGIN_URL=BASE_URL+'/api/users/login';
export const USER_REGISTER_URL=BASE_URL+'/api/users/register';
export const MARBEL_AddMARBEL_URL=MARBEL_URL+'/create';